export type ListingStatus = "active" | "pending" | "sold" | "rented"
export type ListingType = "sale" | "rent"

export interface ListingImage {
  url: string
  alt: string
}

export interface Listing {
  id: string
  title: string
  address: string
  neighborhood: string
  price: number
  type: ListingType
  status: ListingStatus
  beds: number
  baths: number
  sqft: number
  description: string[]
  features: string[]
  images: ListingImage[]
  floorPlanImage?: string
  videoUrl?: string
  dateAdded: string
  dateSold?: string
  
}

export const listings: Listing[] = [
  {
    id: "TheParisian_4C",
    title: "THE PARISIAN is a boutique luxury condominium located in the heart of Astoria",
    address: "30-78 29th Street, Unit 4C",
    neighborhood: "Astoria, NY 11102",
    price: 1055000,
    type: "sale",
    status: "pending",
    beds: 2,
    baths: 2,
    sqft: 759,
    description: [
      "Residence 4C is a thoughtfully designed two-bedroom, two-bathroom home at THE PARISIAN, offering 759 square feet of interior living space and private storage included. The residence features a practical split-bedroom layout, with the living and dining area positioned between both bedrooms to create a comfortable separation between shared and private spaces. A proper entry leads into the open main living area, where the kitchen connects naturally to the room while still feeling clearly defined for everyday use. Interiors are finished in THE PARISIAN’s calm and refined material palette, with oversized floor-to-ceiling windows, 7.5-inch wide-plank white oak flooring, solid wood interior doors, integrated dimmable LED lighting, USB/USB-C outlets throughout, and central heating and cooling with concealed linear diffusers.",
     
      "The kitchen is designed with a clean European sensibility, featuring natural oak cabinetry, Taj Mahal quartz countertops and backsplash in a leathered finish, gas cooking, under-cabinet LED lighting, a Kohler Simplice faucet, and a fully integrated Fisher & Paykel appliance suite with paneled refrigerator and dishwasher.",
      "The bathrooms continue the same understated design language, with oversized porcelain tile, floating vanities with rounded edges, fluted wood detailing, integrated sinks, custom backlit medicine cabinets, Kohler fixtures in warm metallic finishes, hand-finished alabaster lighting, and Nuheat radiant-heated floors.",
      "Additional features include an in-unit washer and dryer, a Comelit smart video intercom system, and a private storage cage included with the residence. With its two-bedroom, two-bathroom layout, practical split-bedroom configuration, elevated finishes, and included private storage, Residence 4C offers a polished and highly functional home within THE PARISIAN.",
      "Residents enjoy a thoughtfully curated amenity collection, including a landscaped rooftop terrace with partially covered lounge areas, outdoor grilling and dining, open-sky gathering space, outdoor cinema, and unobstructed Manhattan skyline views. Additional amenities include a full-height glass-enclosed fitness center with TRUE equipment, a pet spa, bicycle storage, package room, private storage, and 14 on-site deeded parking spaces available for purchase.",
      "Located in the heart of Astoria, THE PARISIAN is surrounded by neighborhood restaurants, cafés, bars, parks, and grocery stores, with convenient access to the N and W trains at 30th Avenue and Broadway. Nearby bus service includes Q104, Q18, Q102, and Q69.",
      "Exclusive Sales and Marketing Agent: Acre NY Realty Inc. Sponsor reserves the right to make changes in accordance with the terms of the offering plan. The complete offering terms are in an Offering Plan available from Sponsor. File No. CD25-0330. Sponsor: 3078 LLC, 2160 North Central Road, Suite 108, Fort Lee, NJ 07024. All artist’s renderings, images, floor plans, finishes, furnishings, amenities, and other details are for representational purposes only and are subject to variances and changes in accordance with the terms of the Offering Plan. Finishes, furnishings, and other items depicted are not necessarily indicative of what will be specified in the Offering Plan or included in the purchase of a unit. Equal Housing Opportunity."
    ],
features: [
     
      "Central air",
      "Washer/Dryer In-Unit",
      "Dishwasher",
      "City View",
      "Balcony",
      "Fitness Center",
      "Roof deck",
      "BBQ Zone",
      "Parking (Garage)",
      "Private Storage (Locker/cage)",
      "Virtual Doorman",
      "Pet Spa",
      "Pets allowed",
      "Bike room",
      "Pied-a-terre allowed",
      "Elevator",
      "Smoke-free",
      "Bike room",
    ],
    images: [
      { url: "/listings/3c.jpg", alt: "Living room with park views" },
      { url: "/listings/3c1.jpg", alt: "Modern chef's kitchen" },
      { url: "/listings/3c2.jpg", alt: "Primary bedroom suite" },
      { url: "/listings/3c3.jpg", alt: "Spa-like bathroom" },
      { url: "/listings/IMG_5137.jpg", alt: "W/D in uint" },
      
  
      { url: "/listings/Parisian.jpg", alt: "The Parisian" },
      { url: "/listings/lobby.jpg", alt: "lobby The Parisian" },
      { url: "/listings/rooftop.jpg", alt: "The Parisian Rooftop" }, 
      { url: "/listings/Parisian_rooftop.jpg", alt: "The Parisian Rooftop TV Zone" },
      { url: "/listings/IMG_5291.jpg", alt: "The Parisian Rooftop Sunset" },
      { url: "/listings/gym.jpg", alt: "The Parisian Gym" },
      { url: "/listings/pet_spa.jpg", alt: "The Parisian Pet Spa" },
    ],
    floorPlanImage: "/listings/4C.jpg",
    videoUrl: "https://www.tiktok.com/@anna_ny_real_estate/video/7649416715868146958",
    dateAdded: "2026-06-15"
  },
  {
    id: "80_Riverside_Boulevard_8E",
    title: "Rare Riverside Gem with a 2500 SF Private Terrace & Hot Tub",
    address: "80 Riverside Boulevard,  Unit 8E",
    neighborhood: "New York, NY 10069",
    price: 2790000,
    type: "sale",
    status: "active",
    beds: 2,
    baths: 2,
    sqft: 1500,
    description: [
      "Welcome to your private sanctuary at The Rushmore, 80 Riverside Boulevard — a stunning convertible 3-bedroom, 2-bath corner residence with one of the largest private terraces on the Upper West Side.",
      "Imagine 2,500 square feet of outdoor space — complete with a hot tub, open sky, and panoramic Hudson River views — perfect for sunset dinners, weekend entertaining, or simply unwinding in the sun.",
      "Inside, floor-to-ceiling windows and soaring ceilings flood the home with natural light, creating a true indoor-outdoor living experience.",
      "Residence Features You’ll Love:",
      "• Full 360° exposure drenched in natural sunlight",
      "• Chef’s Kitchen with Sub-Zero, Viking & Miele appliances, granite counters, and custom cabinetry",
      "• Spacious Primary Suite with spa-like bath (double vanity, soaking tub, and separate shower) plus direct terrace access",
      "• Generously sized 2nd bedroom with great light & storage",
      "• Bonus Room / Home Office — perfect for work-from-home or flexible use",
      "• Private storage unit conveniently located on the terrace",
      "• In-unit washer/dryer & central AC",
      " Building World-Class Amenities:",
      "• 24-hour doorman & concierge",
      "• La Palestra wellness center & health club",
      "• Indoor swimming pool, screening & billiards rooms",
      "• Children’s playroom, bike storage & package room",
      "• Landscaped rooftop terrace with skyline views",
      "All of this just steps from Riverside Park, and minutes to Lincoln Center, Central Park, and the city’s best dining and shopping.",
      "This is more than a home — it’s a lifestyle. Schedule your private showing today and experience Riverside luxury at its finest.",
      
    ],
features: [
     
      "Central air",
      "Washer/Dryer In-Unit",
      "Dishwasher",
      "City View",
      "Terrace 2500 SQFT",
      "Fitness Center",
      "Roof deck",
      "BBQ Zone",
      "Parking (Garage)",
      "Children's playroom",
      "Doorman",
      "Swimming pool",
      "Pets allowed",
      "Bike room",
      "Pied-a-terre allowed",
      "Elevator",
      "Smoke-free",
      "Bike room",
    ],
    images: [
      { url: "/listings/A1.jpg", alt: "80 Riverside Boulevard #8E_1" },
      { url: "/listings/A2.jpg", alt: "80 Riverside Boulevard #8E_2" },
      { url: "/listings/A3.jpg", alt: "80 Riverside Boulevard #8E_3" },
      { url: "/listings/A4.jpg", alt: "80 Riverside Boulevard #8E_4" },
      { url: "/listings/A5.jpg", alt: "80 Riverside Boulevard #8E_5" },
      { url: "/listings/A6.jpg", alt: "80 Riverside Boulevard #8E_6" },
     
    ],
    floorPlanImage: "/listings/A.jpg",
    videoUrl: "https://drive.google.com/file/d/1XjDOIMSd6MDAyrDkj37fFCKONs2Evtgo/view?usp=drive_link",
    dateAdded: "2025-09-25"
  },
  {
    id: "TheParisian_7A",
    title: "THE PARISIAN is a boutique luxury condominium located in the heart of Astoria",
    address: "30-78 29th Street, Unit 7A",
    neighborhood: "Astoria, NY 11102",
    price: 1620000,
    type: "sale",
    status: "active",
    beds: 2,
    baths: 2,
    sqft: 1117,
    description: [
      "Welcome to Residence 7A, a signature penthouse two-bedroom, two-bathroom home at THE PARISIAN, offering 1,117 square feet of interior living space, a 423-square-foot private roof terrace, and private storage included.",
      "The defining feature of Residence 7A is its private roof terrace. Measuring approximately 29'5 by 13'5, the terrace is large enough for outdoor dining, lounge seating, planting, and everyday open-air living. This is not a typical balcony, but a true extension of the home’s living space, a private outdoor room above Astoria, all with unobstructed Manhattan skyline views.",
      "Inside, the residence is designed with a well-proportioned layout that separates the living and entertaining areas from the bedroom wing. The living and dining area offers generous scale, with oversized floor-to-ceiling windows bringing natural light into the home and creating an easy connection between the interior and the terrace.",
      "The interiors are finished in THE PARISIAN’s calm and refined material palette, including 7.5-inch wide-plank white oak flooring, solid wood interior doors, integrated dimmable LED lighting, USB/USB-C outlets throughout, and central heating and cooling with concealed linear diffusers.",
      "The kitchen features natural oak cabinetry, Taj Mahal quartz countertops and backsplash, gas cooking, under-cabinet lighting, Kohler fixtures, and a fully integrated Fisher & Paykel appliance suite. Bathrooms include oversized porcelain tile, floating Taj Mahal quartz vanities, custom backlit medicine cabinets, Kohler fixtures, alabaster lighting, and Nuheat radiant-heated floors.",
      "With its penthouse position, full-size two-bedroom layout, oversized private terrace, skyline views, and included storage, Residence 7A offers one of the most compelling indoor-outdoor living opportunities within THE PARISIAN.",
      "Additional features include an in-unit washer and dryer, a Comelit smart video intercom system, and a private storage cage included with the residence. With its two-bedroom, two-bathroom layout, practical split-bedroom configuration, elevated finishes, and included private storage, Residence 4C offers a polished and highly functional home within THE PARISIAN.",
      "Residents enjoy a thoughtfully curated amenity collection, including a landscaped rooftop terrace with partially covered lounge areas, outdoor grilling and dining, open-sky gathering space, outdoor cinema, and unobstructed Manhattan skyline views. Additional amenities include a full-height glass-enclosed fitness center with TRUE equipment, a pet spa, bicycle storage, package room, private storage, and 14 on-site deeded parking spaces available for purchase.",
      "Located in the heart of Astoria, THE PARISIAN is surrounded by neighborhood restaurants, cafés, bars, parks, and grocery stores, with convenient access to the N and W trains at 30th Avenue and Broadway. Nearby bus service includes Q104, Q18, Q102, and Q69.",
      "Exclusive Sales and Marketing Agent: Acre NY Realty Inc. Sponsor reserves the right to make changes in accordance with the terms of the offering plan. The complete offering terms are in an Offering Plan available from Sponsor. File No. CD25-0330. Sponsor: 3078 LLC, 2160 North Central Road, Suite 108, Fort Lee, NJ 07024. All artist’s renderings, images, floor plans, finishes, furnishings, amenities, and other details are for representational purposes only and are subject to variances and changes in accordance with the terms of the Offering Plan. Finishes, furnishings, and other items depicted are not necessarily indicative of what will be specified in the Offering Plan or included in the purchase of a unit. Equal Housing Opportunity."
    ],
features: [
     
      "Central air",
      "Washer/Dryer In-Unit",
      "Dishwasher",
      "City View",
      "Balcony",
      "Fitness Center",
      "Roof deck",
      "BBQ Zone",
      "Parking (Garage)",
      "Private Storage (Locker/cage)",
      "Virtual Doorman",
      "Pet Spa",
      "Pets allowed",
      "Bike room",
      "Pied-a-terre allowed",
      "Elevator",
      "Smoke-free",
      "Bike room",
    ],
    images: [
      { url: "/listings/7A_1.jpg", alt: "Living room with park views" },
      { url: "/listings/7A_2.jpg", alt: "Modern chef's kitchen" },
      { url: "/listings/7A_3.jpg", alt: "Primary bedroom suite" },
      { url: "/listings/7A_4.jpg", alt: "7A Terrace" },
      { url: "/listings/7A_5.jpg", alt: "The Parisian 7A Terrce" },
      { url: "/listings/3c3.jpg", alt: "Spa-like bathroom" },
      { url: "/listings/IMG_5137.jpg", alt: "W/D in uint" },
      
  
      { url: "/listings/Parisian.jpg", alt: "The Parisian" },
      { url: "/listings/lobby.jpg", alt: "lobby The Parisian" },
      { url: "/listings/rooftop.jpg", alt: "The Parisian Rooftop" }, 
      { url: "/listings/Parisian_rooftop.jpg", alt: "The Parisian Rooftop TV Zone" },
      { url: "/listings/IMG_5291.jpg", alt: "The Parisian Rooftop Sunset" },
      { url: "/listings/gym.jpg", alt: "The Parisian Gym" },
      { url: "/listings/pet_spa.jpg", alt: "The Parisian Pet Spa" },
    ],
    floorPlanImage: "/listings/7A.jpg",
    videoUrl: "https://www.tiktok.com/@anna_ny_real_estate/video/7649416715868146958",
    dateAdded: "2026-06-15"
  },
  {
    id: "TheParisian_3C",
    title: "THE PARISIAN is a boutique luxury condominium located in the heart of Astoria",
    address: "30-78 29th Street, Unit 3C",
    neighborhood: "Astoria, NY 11102",
    price: 1040000,
    type: "sale",
    status: "pending",
    beds: 2,
    baths: 2,
    sqft: 759,
    description: [
      "Residence 3C is a thoughtfully designed two-bedroom, two-bathroom home at THE PARISIAN, offering 759 square feet of interior living space and private storage included. The residence features a practical split-bedroom layout, with the living and dining area positioned between both bedrooms to create a comfortable separation between shared and private spaces. A proper entry leads into the open main living area, where the kitchen connects naturally to the room while still feeling clearly defined for everyday use. Interiors are finished in THE PARISIAN’s calm and refined material palette, with oversized floor-to-ceiling windows, 7.5-inch wide-plank white oak flooring, solid wood interior doors, integrated dimmable LED lighting, USB/USB-C outlets throughout, and central heating and cooling with concealed linear diffusers.",
     
      "The kitchen is designed with a clean European sensibility, featuring natural oak cabinetry, Taj Mahal quartz countertops and backsplash in a leathered finish, gas cooking, under-cabinet LED lighting, a Kohler Simplice faucet, and a fully integrated Fisher & Paykel appliance suite with paneled refrigerator and dishwasher.",
      "The bathrooms continue the same understated design language, with oversized porcelain tile, floating vanities with rounded edges, fluted wood detailing, integrated sinks, custom backlit medicine cabinets, Kohler fixtures in warm metallic finishes, hand-finished alabaster lighting, and Nuheat radiant-heated floors.",
      "Additional features include an in-unit washer and dryer, a Comelit smart video intercom system, and a private storage cage included with the residence. With its two-bedroom, two-bathroom layout, practical split-bedroom configuration, elevated finishes, and included private storage, Residence 3C offers a polished and highly functional home within THE PARISIAN.",
      "Residents enjoy a thoughtfully curated amenity collection, including a landscaped rooftop terrace with partially covered lounge areas, outdoor grilling and dining, open-sky gathering space, outdoor cinema, and unobstructed Manhattan skyline views. Additional amenities include a full-height glass-enclosed fitness center with TRUE equipment, a pet spa, bicycle storage, package room, private storage, and 14 on-site deeded parking spaces available for purchase.",
      "Located in the heart of Astoria, THE PARISIAN is surrounded by neighborhood restaurants, cafés, bars, parks, and grocery stores, with convenient access to the N and W trains at 30th Avenue and Broadway. Nearby bus service includes Q104, Q18, Q102, and Q69.",
      "Exclusive Sales and Marketing Agent: Acre NY Realty Inc. Sponsor reserves the right to make changes in accordance with the terms of the offering plan. The complete offering terms are in an Offering Plan available from Sponsor. File No. CD25-0330. Sponsor: 3078 LLC, 2160 North Central Road, Suite 108, Fort Lee, NJ 07024. All artist’s renderings, images, floor plans, finishes, furnishings, amenities, and other details are for representational purposes only and are subject to variances and changes in accordance with the terms of the Offering Plan. Finishes, furnishings, and other items depicted are not necessarily indicative of what will be specified in the Offering Plan or included in the purchase of a unit. Equal Housing Opportunity."
    ],
features: [
     
      "Central air",
      "Washer/Dryer In-Unit",
      "Dishwasher",
      "City View",
      "Balcony",
      "Fitness Center",
      "Roof deck",
      "BBQ Zone",
      "Parking (Garage)",
      "Private Storage (Locker/cage)",
      "Virtual Doorman",
      "Pet Spa",
      "Pets allowed",
      "Bike room",
      "Pied-a-terre allowed",
      "Elevator",
      "Smoke-free",
      "Bike room",
    ],
    images: [
      { url: "/listings/3c.jpg", alt: "Living room with park views" },
      { url: "/listings/3c1.jpg", alt: "Modern chef's kitchen" },
      { url: "/listings/3c2.jpg", alt: "Primary bedroom suite" },
      { url: "/listings/3c3.jpg", alt: "Spa-like bathroom" },
      { url: "/listings/IMG_5137.jpg", alt: "W/D in uint" },
      
  
       { url: "/listings/Parisian.jpg", alt: "The Parisian" },
      { url: "/listings/lobby.jpg", alt: "lobby The Parisian" },
      { url: "/listings/rooftop.jpg", alt: "The Parisian Rooftop" }, 
      { url: "/listings/Parisian_rooftop.jpg", alt: "The Parisian Rooftop TV Zone" },
      { url: "/listings/IMG_5291.jpg", alt: "The Parisian Rooftop Sunset" },
      { url: "/listings/gym.jpg", alt: "The Parisian Gym" },
      { url: "/listings/pet_spa.jpg", alt: "The Parisian Pet Spa" },
    ],
    floorPlanImage: "/listings/4C.jpg",
    videoUrl: "https://www.tiktok.com/@anna_ny_real_estate/video/7649416715868146958",
    dateAdded: "2026-06-15"
  },
  {
    id: "TheParisian_3B",
    title: "THE PARISIAN is a boutique luxury condominium located in the heart of Astoria",
    address: "30-78 29th Street, Unit 3B",
    neighborhood: "Astoria, NY 11102",
    price: 1040000,
    type: "sale",
    status: "active",
    beds: 2,
    baths: 2,
    sqft: 780,
    description: [
      "Residence 3B is a well-balanced two-bedroom, two-bathroom home at THE PARISIAN, offering 780 square feet of interior living space and private storage included.",
      "The residence is thoughtfully planned with a practical butterfly layout, placing the bedrooms on opposite sides of the home for enhanced privacy and everyday functionality. The living and dining area sits at the center of the residence, creating a natural gathering space while allowing each bedroom to feel more private and independent.",
      "Interiors are finished in THE PARISIAN’s calm and refined material palette, with oversized floor-to-ceiling windows, 7.5-inch wide-plank white oak flooring, solid wood interior doors, integrated dimmable LED lighting, USB/USB-C outlets throughout, and central heating and cooling with concealed linear diffusers.",
      "The kitchen is designed with a clean European sensibility, featuring natural oak cabinetry, Taj Mahal quartz countertops and backsplash in a leathered finish, gas cooking, under-cabinet LED lighting, a Kohler Simplice faucet, and a fully integrated Fisher & Paykel appliance suite with paneled refrigerator and dishwasher.",
      "The bathrooms continue the same understated design language, with oversized porcelain tile, floating vanities with rounded edges, fluted wood detailing, integrated sinks, custom backlit medicine cabinets, Kohler fixtures in warm metallic finishes, hand-finished alabaster lighting, and Nuheat radiant-heated floors.",
      "With its two-bedroom, two-bathroom butterfly layout, enhanced bedroom privacy, elevated finishes, and included private storage, Residence 3B offers a polished and highly functional home within THE PARISIAN.",
      "Additional features include an in-unit washer and dryer, a Comelit smart video intercom system, and a private storage cage included with the residence. With its two-bedroom, two-bathroom layout, practical split-bedroom configuration, elevated finishes, and included private storage, Residence 4C offers a polished and highly functional home within THE PARISIAN.",
      "Residents enjoy a thoughtfully curated amenity collection, including a landscaped rooftop terrace with partially covered lounge areas, outdoor grilling and dining, open-sky gathering space, outdoor cinema, and unobstructed Manhattan skyline views. Additional amenities include a full-height glass-enclosed fitness center with TRUE equipment, a pet spa, bicycle storage, package room, private storage, and 14 on-site deeded parking spaces available for purchase.",
      "Located in the heart of Astoria, THE PARISIAN is surrounded by neighborhood restaurants, cafés, bars, parks, and grocery stores, with convenient access to the N and W trains at 30th Avenue and Broadway. Nearby bus service includes Q104, Q18, Q102, and Q69.",
      "Exclusive Sales and Marketing Agent: Acre NY Realty Inc. Sponsor reserves the right to make changes in accordance with the terms of the offering plan. The complete offering terms are in an Offering Plan available from Sponsor. File No. CD25-0330. Sponsor: 3078 LLC, 2160 North Central Road, Suite 108, Fort Lee, NJ 07024. All artist’s renderings, images, floor plans, finishes, furnishings, amenities, and other details are for representational purposes only and are subject to variances and changes in accordance with the terms of the Offering Plan. Finishes, furnishings, and other items depicted are not necessarily indicative of what will be specified in the Offering Plan or included in the purchase of a unit. Equal Housing Opportunity."
    ],
features: [
     
      "Central air",
      "Washer/Dryer In-Unit",
      "Dishwasher",
      "City View",
      "Balcony",
      "Fitness Center",
      "Roof deck",
      "BBQ Zone",
      "Parking (Garage)",
      "Private Storage (Locker/cage)",
      "Virtual Doorman",
      "Pet Spa",
      "Pets allowed",
      "Bike room",
      "Pied-a-terre allowed",
      "Elevator",
      "Smoke-free",
      "Bike room",
    ],
    images: [
      { url: "/listings/3c.jpg", alt: "Living room with park views" },
      { url: "/listings/3c1.jpg", alt: "Modern chef's kitchen" },
      { url: "/listings/3c2.jpg", alt: "Primary bedroom suite" },
      { url: "/listings/3c3.jpg", alt: "Spa-like bathroom" },
      { url: "/listings/IMG_5137.jpg", alt: "W/D in uint" },
      
  
       { url: "/listings/Parisian.jpg", alt: "The Parisian" },
      { url: "/listings/lobby.jpg", alt: "lobby The Parisian" },
      { url: "/listings/rooftop.jpg", alt: "The Parisian Rooftop" }, 
      { url: "/listings/Parisian_rooftop.jpg", alt: "The Parisian Rooftop TV Zone" },
      { url: "/listings/IMG_5291.jpg", alt: "The Parisian Rooftop Sunset" },
      { url: "/listings/gym.jpg", alt: "The Parisian Gym" },
      { url: "/listings/pet_spa.jpg", alt: "The Parisian Pet Spa" },
    ],
    floorPlanImage: "/listings/3B.jpg",
    videoUrl: "https://www.tiktok.com/@anna_ny_real_estate/video/7649416715868146958",
    dateAdded: "2026-06-15"
  },
  {
    id: "TheParisian_4B",
    title: "THE PARISIAN is a boutique luxury condominium located in the heart of Astoria",
    address: "30-78 29th Street, Unit 4B",
    neighborhood: "Astoria, NY 11102",
    price: 1040000,
    type: "sale",
    status: "pending",
    beds: 2,
    baths: 2,
    sqft: 780,
    description: [
      "Residence 4B is a well-balanced two-bedroom, two-bathroom home at THE PARISIAN, offering 780 square feet of interior living space and private storage included.",
      "The residence is thoughtfully planned with a practical butterfly layout, placing the bedrooms on opposite sides of the home for enhanced privacy and everyday functionality. The living and dining area sits at the center of the residence, creating a natural gathering space while allowing each bedroom to feel more private and independent.",
      "Interiors are finished in THE PARISIAN’s calm and refined material palette, with oversized floor-to-ceiling windows, 7.5-inch wide-plank white oak flooring, solid wood interior doors, integrated dimmable LED lighting, USB/USB-C outlets throughout, and central heating and cooling with concealed linear diffusers.",
      "The kitchen is designed with a clean European sensibility, featuring natural oak cabinetry, Taj Mahal quartz countertops and backsplash in a leathered finish, gas cooking, under-cabinet LED lighting, a Kohler Simplice faucet, and a fully integrated Fisher & Paykel appliance suite with paneled refrigerator and dishwasher.",
      "The bathrooms continue the same understated design language, with oversized porcelain tile, floating vanities with rounded edges, fluted wood detailing, integrated sinks, custom backlit medicine cabinets, Kohler fixtures in warm metallic finishes, hand-finished alabaster lighting, and Nuheat radiant-heated floors.",
      "With its two-bedroom, two-bathroom butterfly layout, enhanced bedroom privacy, elevated finishes, and included private storage, Residence 3B offers a polished and highly functional home within THE PARISIAN.",
      "Additional features include an in-unit washer and dryer, a Comelit smart video intercom system, and a private storage cage included with the residence. With its two-bedroom, two-bathroom layout, practical split-bedroom configuration, elevated finishes, and included private storage, Residence 4C offers a polished and highly functional home within THE PARISIAN.",
      "Residents enjoy a thoughtfully curated amenity collection, including a landscaped rooftop terrace with partially covered lounge areas, outdoor grilling and dining, open-sky gathering space, outdoor cinema, and unobstructed Manhattan skyline views. Additional amenities include a full-height glass-enclosed fitness center with TRUE equipment, a pet spa, bicycle storage, package room, private storage, and 14 on-site deeded parking spaces available for purchase.",
      "Located in the heart of Astoria, THE PARISIAN is surrounded by neighborhood restaurants, cafés, bars, parks, and grocery stores, with convenient access to the N and W trains at 30th Avenue and Broadway. Nearby bus service includes Q104, Q18, Q102, and Q69.",
      "Exclusive Sales and Marketing Agent: Acre NY Realty Inc. Sponsor reserves the right to make changes in accordance with the terms of the offering plan. The complete offering terms are in an Offering Plan available from Sponsor. File No. CD25-0330. Sponsor: 3078 LLC, 2160 North Central Road, Suite 108, Fort Lee, NJ 07024. All artist’s renderings, images, floor plans, finishes, furnishings, amenities, and other details are for representational purposes only and are subject to variances and changes in accordance with the terms of the Offering Plan. Finishes, furnishings, and other items depicted are not necessarily indicative of what will be specified in the Offering Plan or included in the purchase of a unit. Equal Housing Opportunity."
    ],
features: [
     
      "Central air",
      "Washer/Dryer In-Unit",
      "Dishwasher",
      "City View",
      "Balcony",
      "Fitness Center",
      "Roof deck",
      "BBQ Zone",
      "Parking (Garage)",
      "Private Storage (Locker/cage)",
      "Virtual Doorman",
      "Pet Spa",
      "Pets allowed",
      "Bike room",
      "Pied-a-terre allowed",
      "Elevator",
      "Smoke-free",
      "Bike room",
    ],
    images: [
      { url: "/listings/3c.jpg", alt: "Living room with park views" },
      { url: "/listings/3c1.jpg", alt: "Modern chef's kitchen" },
      { url: "/listings/3c2.jpg", alt: "Primary bedroom suite" },
      { url: "/listings/3c3.jpg", alt: "Spa-like bathroom" },
      { url: "/listings/IMG_5137.jpg", alt: "W/D in uint" },
      
  
       { url: "/listings/Parisian.jpg", alt: "The Parisian" },
      { url: "/listings/lobby.jpg", alt: "lobby The Parisian" },
      { url: "/listings/rooftop.jpg", alt: "The Parisian Rooftop" }, 
      { url: "/listings/Parisian_rooftop.jpg", alt: "The Parisian Rooftop TV Zone" },
      { url: "/listings/IMG_5291.jpg", alt: "The Parisian Rooftop Sunset" },
      { url: "/listings/gym.jpg", alt: "The Parisian Gym" },
      { url: "/listings/pet_spa.jpg", alt: "The Parisian Pet Spa" },
    ],
    floorPlanImage: "/listings/3B.jpg",
    videoUrl: "https://www.tiktok.com/@anna_ny_real_estate/video/7649416715868146958",
    dateAdded: "2026-06-15"
  },
  {
    id: "TheParisian_2B",
    title: "THE PARISIAN is a boutique luxury condominium located in the heart of Astoria",
    address: "30-78 29th Street, Unit 2B",
    neighborhood: "Astoria, NY 11102",
    price: 995000,
    type: "sale",
    status: "active",
    beds: 2,
    baths: 2,
    sqft: 780,
    description: [
      "Residence 2B is a well-balanced two-bedroom, two-bathroom home at THE PARISIAN, offering 780 square feet of interior living space and private storage included.",
      "The residence is thoughtfully planned with a practical butterfly layout, placing the bedrooms on opposite sides of the home for enhanced privacy and everyday functionality. The living and dining area sits at the center of the residence, creating a natural gathering space while allowing each bedroom to feel more private and independent.",
      "Interiors are finished in THE PARISIAN’s calm and refined material palette, with oversized floor-to-ceiling windows, 7.5-inch wide-plank white oak flooring, solid wood interior doors, integrated dimmable LED lighting, USB/USB-C outlets throughout, and central heating and cooling with concealed linear diffusers.",
      "The kitchen is designed with a clean European sensibility, featuring natural oak cabinetry, Taj Mahal quartz countertops and backsplash in a leathered finish, gas cooking, under-cabinet LED lighting, a Kohler Simplice faucet, and a fully integrated Fisher & Paykel appliance suite with paneled refrigerator and dishwasher.",
      "The bathrooms continue the same understated design language, with oversized porcelain tile, floating vanities with rounded edges, fluted wood detailing, integrated sinks, custom backlit medicine cabinets, Kohler fixtures in warm metallic finishes, hand-finished alabaster lighting, and Nuheat radiant-heated floors.",
      "With its two-bedroom, two-bathroom butterfly layout, enhanced bedroom privacy, elevated finishes, and included private storage, Residence 2B offers a polished and highly functional home within THE PARISIAN.",
      "Additional features include an in-unit washer and dryer, a Comelit smart video intercom system, and a private storage cage included with the residence. With its two-bedroom, two-bathroom layout, practical split-bedroom configuration, elevated finishes, and included private storage, Residence 4C offers a polished and highly functional home within THE PARISIAN.",
      "Residents enjoy a thoughtfully curated amenity collection, including a landscaped rooftop terrace with partially covered lounge areas, outdoor grilling and dining, open-sky gathering space, outdoor cinema, and unobstructed Manhattan skyline views. Additional amenities include a full-height glass-enclosed fitness center with TRUE equipment, a pet spa, bicycle storage, package room, private storage, and 14 on-site deeded parking spaces available for purchase.",
      "Located in the heart of Astoria, THE PARISIAN is surrounded by neighborhood restaurants, cafés, bars, parks, and grocery stores, with convenient access to the N and W trains at 30th Avenue and Broadway. Nearby bus service includes Q104, Q18, Q102, and Q69.",
      "Exclusive Sales and Marketing Agent: Acre NY Realty Inc. Sponsor reserves the right to make changes in accordance with the terms of the offering plan. The complete offering terms are in an Offering Plan available from Sponsor. File No. CD25-0330. Sponsor: 3078 LLC, 2160 North Central Road, Suite 108, Fort Lee, NJ 07024. All artist’s renderings, images, floor plans, finishes, furnishings, amenities, and other details are for representational purposes only and are subject to variances and changes in accordance with the terms of the Offering Plan. Finishes, furnishings, and other items depicted are not necessarily indicative of what will be specified in the Offering Plan or included in the purchase of a unit. Equal Housing Opportunity."
    ],
features: [
     
      "Central air",
      "Washer/Dryer In-Unit",
      "Dishwasher",
      "City View",
      "Fitness Center",
      "Roof deck",
      "BBQ Zone",
      "Parking (Garage)",
      "Private Storage (Locker/cage)",
      "Virtual Doorman",
      "Pet Spa",
      "Pets allowed",
      "Bike room",
      "Pied-a-terre allowed",
      "Elevator",
      "Smoke-free",
      "Bike room",
    ],
    images: [
      { url: "/listings/3c.jpg", alt: "Living room with park views" },
      { url: "/listings/3c1.jpg", alt: "Modern chef's kitchen" },
      { url: "/listings/3c2.jpg", alt: "Primary bedroom suite" },
      { url: "/listings/3c3.jpg", alt: "Spa-like bathroom" },
      { url: "/listings/IMG_5137.jpg", alt: "W/D in uint" },
      
  
       { url: "/listings/Parisian.jpg", alt: "The Parisian" },
      { url: "/listings/lobby.jpg", alt: "lobby The Parisian" },
      { url: "/listings/rooftop.jpg", alt: "The Parisian Rooftop" }, 
      { url: "/listings/Parisian_rooftop.jpg", alt: "The Parisian Rooftop TV Zone" },
      { url: "/listings/IMG_5291.jpg", alt: "The Parisian Rooftop Sunset" },
      { url: "/listings/gym.jpg", alt: "The Parisian Gym" },
      { url: "/listings/pet_spa.jpg", alt: "The Parisian Pet Spa" },
    ],
    floorPlanImage: "/listings/3B.jpg",
    videoUrl: "https://www.tiktok.com/@anna_ny_real_estate/video/7649416715868146958",
    dateAdded: "2026-06-15"
  },
  {
    id: "TheParisian_3D",
    title: "THE PARISIAN is a boutique luxury condominium located in the heart of Astoria",
    address: "30-78 29th Street, Unit 3D",
    neighborhood: "Astoria, NY 11102",
    price: 798000,
    type: "sale",
    status: "active",
    beds: 1,
    baths: 1,
    sqft: 578,
    description: [
       "Residence 3D is a well-composed one-bedroom home at THE PARISIAN, offering 578 square feet of interior living space and private storage included.",
      "The residence is efficiently planned for everyday livability, with a practical layout that balances comfort, function, and refined design. The main living area offers a flexible setting for lounging and dining, while the bedroom provides a comfortable private retreat within the home.",
      "Interiors are finished in THE PARISIAN’s calm and refined material palette, with oversized floor-to-ceiling windows, 7.5-inch wide-plank white oak flooring, solid wood interior doors, custom built-in closets, integrated dimmable LED lighting, USB/USB-C outlets throughout, and central heating and cooling with concealed linear diffusers.",
      "The kitchen is designed with a clean European sensibility, featuring natural oak cabinetry, Taj Mahal quartz countertops and backsplash in a leathered finish, gas cooking, under-cabinet LED lighting, a Kohler Simplice faucet, and a fully integrated Fisher & Paykel appliance suite with paneled refrigerator and dishwasher.",
      "The bathroom continues the same understated design language, with oversized porcelain tile, a floating vanity with rounded edges, fluted wood detailing, an integrated sink, a custom backlit medicine cabinet, Kohler fixtures in warm metallic finishes, hand-finished alabaster lighting, and Nuheat radiant-heated floors.",
      "With its efficient one-bedroom layout, elevated finishes, custom built-in closets, and included private storage, Residence 3D offers a polished and highly functional home within THE PARISIAN.",
      "Additional features include an in-unit washer and dryer, a Comelit smart video intercom system, and a private storage cage included with the residence. With its two-bedroom, two-bathroom layout, practical split-bedroom configuration, elevated finishes, and included private storage, Residence 4C offers a polished and highly functional home within THE PARISIAN.",
      "Residents enjoy a thoughtfully curated amenity collection, including a landscaped rooftop terrace with partially covered lounge areas, outdoor grilling and dining, open-sky gathering space, outdoor cinema, and unobstructed Manhattan skyline views. Additional amenities include a full-height glass-enclosed fitness center with TRUE equipment, a pet spa, bicycle storage, package room, private storage, and 14 on-site deeded parking spaces available for purchase.",
      "Located in the heart of Astoria, THE PARISIAN is surrounded by neighborhood restaurants, cafés, bars, parks, and grocery stores, with convenient access to the N and W trains at 30th Avenue and Broadway. Nearby bus service includes Q104, Q18, Q102, and Q69.",
      "Exclusive Sales and Marketing Agent: Acre NY Realty Inc. Sponsor reserves the right to make changes in accordance with the terms of the offering plan. The complete offering terms are in an Offering Plan available from Sponsor. File No. CD25-0330. Sponsor: 3078 LLC, 2160 North Central Road, Suite 108, Fort Lee, NJ 07024. All artist’s renderings, images, floor plans, finishes, furnishings, amenities, and other details are for representational purposes only and are subject to variances and changes in accordance with the terms of the Offering Plan. Finishes, furnishings, and other items depicted are not necessarily indicative of what will be specified in the Offering Plan or included in the purchase of a unit. Equal Housing Opportunity."
    ],
features: [
     
      "Central air",
      "Washer/Dryer In-Unit",
      "Dishwasher",
      "City View",
      "Fitness Center",
      "Roof deck",
      "BBQ Zone",
      "Parking (Garage)",
      "Private Storage (Locker/cage)",
      "Virtual Doorman",
      "Pet Spa",
      "Pets allowed",
      "Bike room",
      "Pied-a-terre allowed",
      "Elevator",
      "Smoke-free",
      "Bike room",
    ],
    images: [
      { url: "/listings/3c.jpg", alt: "Living room with park views" },
      { url: "/listings/3c1.jpg", alt: "Modern chef's kitchen" },
      { url: "/listings/3c2.jpg", alt: "Primary bedroom suite" },
      { url: "/listings/3c3.jpg", alt: "Spa-like bathroom" },
      { url: "/listings/IMG_5137.jpg", alt: "W/D in uint" },
      
  
       { url: "/listings/Parisian.jpg", alt: "The Parisian" },
      { url: "/listings/lobby.jpg", alt: "lobby The Parisian" },
      { url: "/listings/rooftop.jpg", alt: "The Parisian Rooftop" }, 
      { url: "/listings/Parisian_rooftop.jpg", alt: "The Parisian Rooftop TV Zone" },
      { url: "/listings/IMG_5291.jpg", alt: "The Parisian Rooftop Sunset" },
      { url: "/listings/gym.jpg", alt: "The Parisian Gym" },
      { url: "/listings/pet_spa.jpg", alt: "The Parisian Pet Spa" },
    ],
    floorPlanImage: "/listings/3D.jpg",
    videoUrl: "https://www.tiktok.com/@anna_ny_real_estate/video/7649416715868146958",
    dateAdded: "2026-06-15"
  },
  {
    id: "TheParisian_3A",
    title: "THE PARISIAN is a boutique luxury condominium located in the heart of Astoria",
    address: "30-78 29th Street, Unit 3A",
    neighborhood: "Astoria, NY 11102",
    price: 855000,
    type: "sale",
    status: "active",
    beds: 1,
    baths: 1,
    sqft: 621,
    description: [
      "Welcome to Residence 3A, a well-composed 621-square-foot one-bedroom home with private storage, a practical layout, and elevated finishes. Thoughtfully planned and easy to live in, the home feels both functional and refined.",
      "The residence is finished in THE PARISIAN’s calm and refined material palette, with oversized floor-to-ceiling windows, 7.5-inch wide-plank white oak flooring, solid wood interior doors, custom built-in closets, integrated dimmable LED lighting, and USB/USB-C outlets throughout.",
      "The kitchen is designed with a clean European sensibility, combining natural oak cabinetry, Taj Mahal quartz countertops and backsplash in a leathered finish, and a fully integrated Fisher & Paykel appliance suite. Gas cooking, under-cabinet LED lighting, a Kohler Simplice faucet, and a fully integrated appliance suite with paneled refrigerator and dishwasher complete a kitchen that feels polished, practical, and easy to live with.",
      "The bathroom continues the home’s elevated yet understated design language, featuring oversized porcelain tile, a floating Taj Mahal quartz vanity with rounded edges, fluted wood detailing, an integrated sink, a custom backlit medicine cabinet, Kohler fixtures in warm metallic finishes, hand-finished alabaster lighting, and Nuheat radiant-heated floors. Additional features include central heating and cooling with concealed linear diffusers, an in-unit washer and dryer, a Comelit smart video intercom system, and a private storage cage included with the residence.",
      "Additional features include an in-unit washer and dryer, a Comelit smart video intercom system, and a private storage cage included with the residence. With its two-bedroom, two-bathroom layout, practical split-bedroom configuration, elevated finishes, and included private storage, Residence 4C offers a polished and highly functional home within THE PARISIAN.",
      "Residents enjoy a thoughtfully curated amenity collection, including a landscaped rooftop terrace with partially covered lounge areas, outdoor grilling and dining, open-sky gathering space, outdoor cinema, and unobstructed Manhattan skyline views. Additional amenities include a full-height glass-enclosed fitness center with TRUE equipment, a pet spa, bicycle storage, package room, private storage, and 14 on-site deeded parking spaces available for purchase.",
      "Located in the heart of Astoria, THE PARISIAN is surrounded by neighborhood restaurants, cafés, bars, parks, and grocery stores, with convenient access to the N and W trains at 30th Avenue and Broadway. Nearby bus service includes Q104, Q18, Q102, and Q69.",
      "Exclusive Sales and Marketing Agent: Acre NY Realty Inc. Sponsor reserves the right to make changes in accordance with the terms of the offering plan. The complete offering terms are in an Offering Plan available from Sponsor. File No. CD25-0330. Sponsor: 3078 LLC, 2160 North Central Road, Suite 108, Fort Lee, NJ 07024. All artist’s renderings, images, floor plans, finishes, furnishings, amenities, and other details are for representational purposes only and are subject to variances and changes in accordance with the terms of the Offering Plan. Finishes, furnishings, and other items depicted are not necessarily indicative of what will be specified in the Offering Plan or included in the purchase of a unit. Equal Housing Opportunity."
    ],
features: [
     
      "Central air",
      "Washer/Dryer In-Unit",
      "Dishwasher",
      "City View",
      "Fitness Center",
      "Roof deck",
      "BBQ Zone",
      "Parking (Garage)",
      "Private Storage (Locker/cage)",
      "Virtual Doorman",
      "Pet Spa",
      "Pets allowed",
      "Bike room",
      "Pied-a-terre allowed",
      "Elevator",
      "Smoke-free",
      "Bike room",
    ],
    images: [
      { url: "/listings/3c.jpg", alt: "Living room with park views" },
      { url: "/listings/3c1.jpg", alt: "Modern chef's kitchen" },
      { url: "/listings/3c2.jpg", alt: "Primary bedroom suite" },
      { url: "/listings/3c3.jpg", alt: "Spa-like bathroom" },
      { url: "/listings/IMG_5137.jpg", alt: "W/D in uint" },
      
  
       { url: "/listings/Parisian.jpg", alt: "The Parisian" },
      { url: "/listings/lobby.jpg", alt: "lobby The Parisian" },
      { url: "/listings/rooftop.jpg", alt: "The Parisian Rooftop" }, 
      { url: "/listings/Parisian_rooftop.jpg", alt: "The Parisian Rooftop TV Zone" },
      { url: "/listings/IMG_5291.jpg", alt: "The Parisian Rooftop Sunset" },
      { url: "/listings/gym.jpg", alt: "The Parisian Gym" },
      { url: "/listings/pet_spa.jpg", alt: "The Parisian Pet Spa" },
    ],
    floorPlanImage: "/listings/3A.jpg",
    videoUrl: "https://www.tiktok.com/@anna_ny_real_estate/video/7649416715868146958",
    dateAdded: "2026-06-15"
  },
   {
    id: "TheParisian_1A",
    title: "THE PARISIAN is a boutique luxury condominium located in the heart of Astoria",
    address: "30-78 29th Street, Unit 1A",
    neighborhood: "Astoria, NY 11102",
    price: 585000,
    type: "sale",
    status: "active",
    beds: 0,
    baths: 1,
    sqft: 481,
    description: [
      "Residence 1A is a thoughtfully designed studio home at THE PARISIAN, offering 481 square feet of interior living space and private storage included.",
      "The residence features a smart, well-defined layout with a proper entry that creates a clear sense of arrival. The kitchen and bathroom are efficiently positioned to keep the main living area open and flexible, allowing the home to comfortably support lounging, dining, sleeping, and work-from-home use.",
      "Interiors are finished in THE PARISIAN’s calm and refined material palette, with oversized floor-to-ceiling windows, 7.5-inch wide-plank white oak flooring, solid wood interior doors, integrated dimmable LED lighting, USB/USB-C outlets throughout, and central heating and cooling with concealed linear diffusers.",
      "The kitchen is designed with a clean European sensibility, featuring natural oak cabinetry, Taj Mahal quartz countertops and backsplash in a leathered finish, gas cooking, under-cabinet LED lighting, a Kohler Simplice faucet, and a fully integrated Fisher & Paykel appliance suite with paneled refrigerator and dishwasher.",
      "The bathroom continues the same understated design language, with oversized porcelain tile, a floating vanity with rounded edges, fluted wood detailing, an integrated sink, a custom backlit medicine cabinet, Kohler fixtures in warm metallic finishes, hand-finished alabaster lighting, and Nuheat radiant-heated floors.",
      "With its efficient layout, elevated finishes, proper entry sequence, and included private storage, Residence 1A offers a polished and highly functional studio residence within THE PARISIAN.",
      "Additional features include an in-unit washer and dryer, a Comelit smart video intercom system, and a private storage cage included with the residence. With its two-bedroom, two-bathroom layout, practical split-bedroom configuration, elevated finishes, and included private storage, Residence 4C offers a polished and highly functional home within THE PARISIAN.",
      "Residents enjoy a thoughtfully curated amenity collection, including a landscaped rooftop terrace with partially covered lounge areas, outdoor grilling and dining, open-sky gathering space, outdoor cinema, and unobstructed Manhattan skyline views. Additional amenities include a full-height glass-enclosed fitness center with TRUE equipment, a pet spa, bicycle storage, package room, private storage, and 14 on-site deeded parking spaces available for purchase.",
      "Located in the heart of Astoria, THE PARISIAN is surrounded by neighborhood restaurants, cafés, bars, parks, and grocery stores, with convenient access to the N and W trains at 30th Avenue and Broadway. Nearby bus service includes Q104, Q18, Q102, and Q69.",
      "Exclusive Sales and Marketing Agent: Acre NY Realty Inc. Sponsor reserves the right to make changes in accordance with the terms of the offering plan. The complete offering terms are in an Offering Plan available from Sponsor. File No. CD25-0330. Sponsor: 3078 LLC, 2160 North Central Road, Suite 108, Fort Lee, NJ 07024. All artist’s renderings, images, floor plans, finishes, furnishings, amenities, and other details are for representational purposes only and are subject to variances and changes in accordance with the terms of the Offering Plan. Finishes, furnishings, and other items depicted are not necessarily indicative of what will be specified in the Offering Plan or included in the purchase of a unit. Equal Housing Opportunity."
    ],
features: [
     
      "Central air",
      "Washer/Dryer In-Unit",
      "Dishwasher",
      "City View",
      "Fitness Center",
      "Roof deck",
      "BBQ Zone",
      "Parking (Garage)",
      "Private Storage (Locker/cage)",
      "Virtual Doorman",
      "Pet Spa",
      "Pets allowed",
      "Bike room",
      "Pied-a-terre allowed",
      "Elevator",
      "Smoke-free",
      "Bike room",
    ],
    images: [
      { url: "/listings/3c.jpg", alt: "Living room with park views" },
      { url: "/listings/3c1.jpg", alt: "Modern chef's kitchen" },
      { url: "/listings/3c2.jpg", alt: "Primary bedroom suite" },
      { url: "/listings/3c3.jpg", alt: "Spa-like bathroom" },
      { url: "/listings/IMG_5137.jpg", alt: "W/D in uint" },
      
  
       { url: "/listings/Parisian.jpg", alt: "The Parisian" },
      { url: "/listings/lobby.jpg", alt: "lobby The Parisian" },
      { url: "/listings/rooftop.jpg", alt: "The Parisian Rooftop" }, 
      { url: "/listings/Parisian_rooftop.jpg", alt: "The Parisian Rooftop TV Zone" },
      { url: "/listings/IMG_5291.jpg", alt: "The Parisian Rooftop Sunset" },
      { url: "/listings/gym.jpg", alt: "The Parisian Gym" },
      { url: "/listings/pet_spa.jpg", alt: "The Parisian Pet Spa" },
    ],
    floorPlanImage: "/listings/1A.jpg",
    videoUrl: "https://www.tiktok.com/@anna_ny_real_estate/video/7649416715868146958",
    dateAdded: "2026-06-15"
  },
   {
    id: "TheParisian_3E",
    title: "THE PARISIAN is a boutique luxury condominium located in the heart of Astoria",
    address: "30-78 29th Street, Unit 3E",
    neighborhood: "Astoria, NY 11102",
    price: 598000,
    type: "sale",
    status: "active",
    beds: 0,
    baths: 1,
    sqft: 425,
    description: [
      "Residence 3E is a thoughtfully planned studio home at THE PARISIAN, offering 425 square feet of interior living space and private storage included.",
      "The residence pairs efficient design with a bright, open feel. A defined entry sequence, dedicated closet space, and a well-resolved main living area create a more composed and livable take on studio living, with flexibility for lounging, dining, sleeping, and work-from-home use.",
      "Interiors are finished in THE PARISIAN’s calm and refined material palette, with oversized floor-to-ceiling windows, 7.5-inch wide-plank white oak flooring, solid wood interior doors, custom built-in closets, integrated dimmable LED lighting, USB/USB-C outlets throughout, and central heating and cooling with concealed linear diffusers.",
      "The kitchen is designed with a clean European sensibility, featuring natural oak cabinetry, Taj Mahal quartz countertops and backsplash in a leathered finish, gas cooking, under-cabinet LED lighting, a Kohler Simplice faucet, and a fully integrated Fisher & Paykel appliance suite with paneled refrigerator and dishwasher.",
      "The bathroom continues the same understated design language, with oversized porcelain tile, a floating vanity with rounded edges, fluted wood detailing, an integrated sink, a custom backlit medicine cabinet, Kohler fixtures in warm metallic finishes, hand-finished alabaster lighting, and Nuheat radiant-heated floors.",
      "With its efficient layout, dedicated closet space, elevated finishes, and included private storage, Residence 3E offers a polished and highly functional studio residence within THE PARISIAN.",
      "Additional features include an in-unit washer and dryer, a Comelit smart video intercom system, and a private storage cage included with the residence. With its two-bedroom, two-bathroom layout, practical split-bedroom configuration, elevated finishes, and included private storage, Residence 4C offers a polished and highly functional home within THE PARISIAN.",
      "Residents enjoy a thoughtfully curated amenity collection, including a landscaped rooftop terrace with partially covered lounge areas, outdoor grilling and dining, open-sky gathering space, outdoor cinema, and unobstructed Manhattan skyline views. Additional amenities include a full-height glass-enclosed fitness center with TRUE equipment, a pet spa, bicycle storage, package room, private storage, and 14 on-site deeded parking spaces available for purchase.",
      "Located in the heart of Astoria, THE PARISIAN is surrounded by neighborhood restaurants, cafés, bars, parks, and grocery stores, with convenient access to the N and W trains at 30th Avenue and Broadway. Nearby bus service includes Q104, Q18, Q102, and Q69.",
      "Exclusive Sales and Marketing Agent: Acre NY Realty Inc. Sponsor reserves the right to make changes in accordance with the terms of the offering plan. The complete offering terms are in an Offering Plan available from Sponsor. File No. CD25-0330. Sponsor: 3078 LLC, 2160 North Central Road, Suite 108, Fort Lee, NJ 07024. All artist’s renderings, images, floor plans, finishes, furnishings, amenities, and other details are for representational purposes only and are subject to variances and changes in accordance with the terms of the Offering Plan. Finishes, furnishings, and other items depicted are not necessarily indicative of what will be specified in the Offering Plan or included in the purchase of a unit. Equal Housing Opportunity."
    ],
features: [
     
      "Central air",
      "Washer/Dryer In-Unit",
      "Dishwasher",
      "City View",
      "Fitness Center",
      "Roof deck",
      "BBQ Zone",
      "Parking (Garage)",
      "Private Storage (Locker/cage)",
      "Virtual Doorman",
      "Pet Spa",
      "Pets allowed",
      "Bike room",
      "Pied-a-terre allowed",
      "Elevator",
      "Smoke-free",
      "Bike room",
    ],
    images: [
      { url: "/listings/3c.jpg", alt: "Living room with park views" },
      { url: "/listings/3c1.jpg", alt: "Modern chef's kitchen" },
      { url: "/listings/3c2.jpg", alt: "Primary bedroom suite" },
      { url: "/listings/3c3.jpg", alt: "Spa-like bathroom" },
      { url: "/listings/IMG_5137.jpg", alt: "W/D in uint" },
      
  
       { url: "/listings/Parisian.jpg", alt: "The Parisian" },
      { url: "/listings/lobby.jpg", alt: "lobby The Parisian" },
      { url: "/listings/rooftop.jpg", alt: "The Parisian Rooftop" }, 
      { url: "/listings/Parisian_rooftop.jpg", alt: "The Parisian Rooftop TV Zone" },
      { url: "/listings/IMG_5291.jpg", alt: "The Parisian Rooftop Sunset" },
      { url: "/listings/gym.jpg", alt: "The Parisian Gym" },
      { url: "/listings/pet_spa.jpg", alt: "The Parisian Pet Spa" },
    ],
    floorPlanImage: "/listings/3E.jpg",
    videoUrl: "https://www.tiktok.com/@anna_ny_real_estate/video/7649416715868146958",
    dateAdded: "2026-06-15"
  },
 
    // RENT listings 
  {
    id: "300_West_30th_Street_PHB",
    title: "Penthouse B at 300 West 30th Street, a premium 1-bedroom, 1-bathroom apartmen",
    address: "300 West 30th Street, Unit PHB",
    neighborhood: "Chelsea, NY, 10001",
    price: 6300,
    type: "rent",
    status: "rented",
    beds: 1,
    baths: 1,
    sqft: 622,
    description: [
      "Welcome to Penthouse B at 300 West 30th Street, a premium 1-bedroom, 1-bathroom apartment on the highest residential floor. With only two units on this level, this pristine penthouse offers an exceptionally quiet, private, and elevated living experience on the Chelsea and Penn District border.",
      "Dramatic floor-to-ceiling windows flood the apartment with natural light from its southwest exposure and frame serene garden views. The open-concept layout features wide-plank white oak flooring and a windowed chef's kitchen custom designed by Workshop/APD, complete with integrated Miele appliances and white marble countertops. The king-size bedroom offers deep custom closets, while the spa-like bath features radiant heated floors. An in-unit Miele washer and dryer is included for ultimate convenience.",
      "Residents enjoy luxury amenities including a 24-hour doorman, a modern fitness center, a second-floor courtyard with grills, and a 12th-floor Sky Terrace with views of Hudson Yards and the Empire State Building. Co-working lounges and bike storage are also available.",
      "Located moments from Moynihan Train Hall and Penn Station, you have immediate access to over ten subway lines and PATH trains. The High Line, Hudson Yards, and Chelsea galleries are all just a short walk away. Available for immediate occupancy. Please contact us to schedule a private tour.",
    ],
    features: [
      "Pets allowed",
      "Central air",
      "View City, Skyline",
      "Chef's Kitchen",
      "Miele Appliances",
      "Washer/Dryer",
      "Dishwasher",
      "Bike room",
      "Elevator",
      "Package room",
      "Concierge",
      "Laundry in building",
      "Storage space",
      "Doorman",
      "Live-in super",
      "Gym",
      "Media room",
      "Garden",
      "Roof deck",
    ],
    images: [
      { url: "/listings/PHB1.jpg", alt: "Dramatic loft living space" },
      { url: "/listings/PHB2.jpg", alt: "Chef's kitchen" },
      { url: "/listings/PHB3.jpg", alt: "Primary bedroom" },
      { url: "/listings/PHB4.jpg", alt: "Architectural details" },
      { url: "/listings/PHB5.jpg", alt: "Dramatic loft living space" },
      { url: "/listings/PHB6.jpg", alt: "Chef's kitchen" },
      { url: "/listings/PHB7.jpg", alt: "Primary bedroom" },
      { url: "/listings/PHB8.jpg", alt: "Architectural details" },
    ],
    floorPlanImage: "/listings/PHB.jpg",
    videoUrl: "https://www.tiktok.com/@annabnn/video/example5",
    dateAdded: "2026-06-10"
  },

  // Archived listings (sold/rented)
  {
    id: "2934_Brighton_Fourth_Street_Unit_D",
    title: "This bright and spacious 2-bedroom, 1.5-bath duplex",
    address: "2934 Brighton Fourth Street, Unit D",
    neighborhood: "Brooklyn, Brighton Beach , NY 11235",
    price: 600000,
    type: "sale",
    status: "sold",
    beds: 2,
    baths: 1.5,
    sqft: 950,
    description: [
     "Welcome to 2934 Brighton 4th Street — a boutique 6-unit condominium with elevator access, parking, and a shared rooftop terrace, ideally located just minutes from the beach, shopping, and public transportation. Conveniently located within walking distance to the B and Q subway lines",
     "This bright and spacious 2-bedroom, 1.5-bath duplex is located on the 3rd and 4th floors and offers a perfect blend of comfort and functionality. The home features wide plank hardwood floors, eastern and southern exposures, and two private balconies that fill the space with natural light.",
     "The open-concept living and dining area flows into a modern kitchen equipped with stainless steel appliances, a gas stove, dishwasher, microwave, large refrigerator, and a convenient window above the cooking area.",
     "A powder room, in-unit washer/dryer, and balcony complete the main floor. Upstairs, you'll find two sunny bedrooms, an elegant full bathroom with a relaxing soaking tub, and an additional private entry to the hallway. The primary bedroom features a walk-in closet and private balcony.",
      "Additional highlights include :",
      " Split A/C systems on both floors",
      "• Strong wood staircase",
      "• Private gated parking space with electric car charging",
      "• Dedicated storage room",
      "• Shared rooftop terrace perfect for BBQs or entertaining",
     "Each apartment in the building includes its own boiler and pump, ensuring efficient utility control.Experience modern Brighton Beach living in this sun-filled, well-maintained condo — perfect for homeowners or investors alike. Some of the photos depicted are virtually staged.",
    ],
features: [
     
      "Split Systems",
      "Washer/Dryer In-Unit",
      "Dishwasher",
      "City View",
      "Roof deck",
      "BBQ Zone",
      "Parking (Garage)",
      "Private Storage (Locker/cage)",
      "Virtual Doorman",
      "Pets allowed",
      "Bike room",
      "Elevator",
      "Smoke-free",
      "Bike room",
    ],
    images: [
      { url: "/listings/BR_2.jpg", alt: "2934_Brighton_Fourth_Street_Unit_D_1" },
      { url: "/listings/BR_3.jpg", alt: "2934_Brighton_Fourth_Street_Unit_D_2" },
      { url: "/listings/BR_4.jpg", alt: "2934_Brighton_Fourth_Street_Unit_D_3" },
      { url: "/listings/BR_5.jpg", alt: "2934_Brighton_Fourth_Street_Unit_D_4" },
      { url: "/listings/BR_6.jpg", alt: "2934_Brighton_Fourth_Street_Unit_D_5" },
      { url: "/listings/BR_7.jpg", alt: "2934_Brighton_Fourth_Street_Unit_D_6" },
      { url: "/listings/BR_8.jpg", alt: "2934_Brighton_Fourth_Street_Unit_D_7" },
      { url: "/listings/BR_9.jpg", alt: "2934_Brighton_Fourth_Street_Unit_D_8" }, 
      { url: "/listings/BR_10.jpg", alt: "2934_Brighton_Fourth_Street_Unit_D_9" },
     
    ],
    floorPlanImage: "/listings/BR_1.jpg",
    videoUrl: "https://www.tiktok.com/@anna_ny_real_estate/video/7573050666369797431",
    dateAdded: "2025-11-15",
    dateSold: "2026-04-12"
  },
  {
    id: "3Eleven_2419",
    title: "3ELEVEN, a premium 1-bedroom, 1-bathroom apartmen",
    address: "311 11th Avenue, Unit 2419",
    neighborhood: "Chelsea, NY, 10001",
    price: 4995,
    type: "rent",
    status: "rented",
    beds: 1,
    baths: 1,
    sqft: 590,
    description: [
     ""
    ],
    features: [
      "Pets allowed",
      "Central air",
      "View City, Skyline",
      "Chef's Kitchen",
      "Miele Appliances",
      "Washer/Dryer",
      "Dishwasher",
      "Bike room",
      "Elevator",
      "Package room",
      "Concierge",
      "Laundry in building",
      "Storage space",
      "Doorman",
      "Live-in super",
      "Gym",
      "Media room",
      "Garden",
      "Roof deck",
    ],
    images: [
      { url: "/listings/3Eleven1.jpg", alt: "Dramatic loft living space" },
      { url: "/listings/3Eleven2.jpg", alt: "Chef's kitchen" },
      { url: "/listings/3Eleven3.jpg", alt: "Primary bedroom" },
      { url: "/listings/3Eleven4.jpg", alt: "Architectural details" },
     
    ],
    floorPlanImage: "/listings/3Eleven.jpg",
    videoUrl: "https://www.tiktok.com/@anna_ny_real_estate/video/7566841909398752526",
    dateAdded: "2026-06-10",
   
  },
  {
    id: "TheForten_1610",
    title: "Forten at Columbia, a premium 1-bedroom, 1-bathroom apartmen",
    address: "410 West 126th Street, Unit 1610",
    neighborhood: "West Harlem, NY, 10027",
    price: 4116,
    type: "rent",
    status: "rented",
    beds: 1,
    baths: 1,
    sqft: 622,
    description: [
      ""
    ],
    features: [
      "Pets allowed",
      "Central air",
      "View City, Skyline",
      "Chef's Kitchen",
      "Miele Appliances",
      "Washer/Dryer",
      "Dishwasher",
      "Bike room",
      "Elevator",
      "Package room",
      "Concierge",
      "Laundry in building",
      "Storage space",
      "Doorman",
      "Live-in super",
      "Gym",
      "Media room",
      "Garden",
      "Roof deck",
    ],
    images: [
      { url: "/listings/Forten1.jpg", alt: "Dramatic loft living space" },
      { url: "/listings/Forten2.jpg", alt: "Chef's kitchen" },
      { url: "/listings/Forten3.jpg", alt: "Primary bedroom" },
      { url: "/listings/Forten4.jpg", alt: "Architectural details" },
     
    ],
    floorPlanImage: "/listings/Forten.jpg",
    videoUrl: "https://www.tiktok.com/@anna_ny_real_estate/video/7551257153990921486",
    dateAdded: "2026-01-04"
  },
  {
    id: "TheSoMa_3219",
    title: "The Soma, Studio + Office",
    address: "25 Water Street, Unit 3219",
    neighborhood: "Financial District,  New York, NY 10004",
    price: 5150,
    type: "rent",
    status: "rented",
    beds: 0,
    baths: 1,
    sqft: 400,
    description: [
     ""
    ],
    features: [
      "Pets allowed",
      "Central air",
      "View City, Skyline",
      "Chef's Kitchen",
      "Miele Appliances",
      "Washer/Dryer",
      "Dishwasher",
      "Bike room",
      "Elevator",
      "Package room",
      "Concierge",
      "Laundry in building",
      "Storage space",
      "Doorman",
      "Live-in super",
      "Gym",
      "Media room",
      "Garden",
      "Roof deck",
    ],
    images: [
      { url: "/listings/Soma1.jpg", alt: "Dramatic loft living space" },
      { url: "/listings/Soma2.jpg", alt: "Chef's kitchen" },
      { url: "/listings/Soma3.jpg", alt: "Primary bedroom" },
      { url: "/listings/Soma4.jpg", alt: "Architectural details" },
     
    ],
    floorPlanImage: "/listings/Soma.jpg",
    videoUrl: "https://www.tiktok.com/@anna_ny_real_estate/video/7487654460852817195",
    dateAdded: "2026-06-18"
  },
  
]

// Helper functions
export function getActiveListings(): Listing[] {
  return listings.filter(l => l.status === "active" || l.status === "pending")
}

export function getArchivedListings(): Listing[] {
  return listings.filter(l => l.status === "sold" || l.status === "rented")
}

export function getListingById(id: string): Listing | undefined {
  return listings.find(l => l.id === id)
}

export function getListingsByType(type: ListingType): Listing[] {
  return listings.filter(l => l.type === type)
}

export function formatPrice(price: number, type: ListingType): string {
  if (type === "rent") {
    return `$${price.toLocaleString()}/mo`
  }
  return `$${price.toLocaleString()}`
}
